# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LocationManagerExample' do

end

target 'LocationManagerTests' do
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end

